services:
  postgres:
    image: postgres:16.2
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grocery
    ports:
      - "5432:5432"
  
  nest:
    build:
      context: .
      dockerfile: dockerfile
    container_name: qp-assessment-grocery
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      # POSTGRES_HOST: postgres
      # POSTGRES_PORT: 5432
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: root
      # POSTGRES_DB: grocery
      DB_NAME: grocery
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_HOST: postgres
      DB_PORT: 5432